services:
  mysql:
    image: mysql:8.0
    container_name: cadastro_bd
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: data_base_crud
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
      TZ: America/Sao_Paulo
    command:
      - --default-time-zone=America/Sao_Paulo
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql-mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-db.d
volumes:
  mysql_data:
